package ui

const (
	AppName                        = "Mihari"
	Connecting                     = "Connecting to the Mihari daemon…"
	ResizeRequired                 = "Terminal too small"
	ResizeInstructions             = "Resize to at least 72×22. Press ? for help or q to quit."
	UnavailableTitle               = "Unavailable"
	UnavailableReason              = "This page is waiting for daemon capability support."
	ConfigNotAppliedLabel          = "Not applied"
	NoActiveSubscriptionLabel      = "No active subscription"
	NoSubscriptionsConfiguredLabel = "None configured"
	FooterRail                     = "↑/↓ page  Enter open  ? help  q quit"
	FooterContent                  = "Esc back  ? help  q quit"
	FooterOverview                 = "Esc back  ? help  q quit"
	FooterProxies                  = "Esc back  Enter expand  t test  Ctrl+T test all  ? help  q quit"
	FooterConnections              = "Esc back  / search  x close  p pause  Enter details  ? help  q quit"
	FooterRules                    = "Esc back  / search  r reload  u update  Ctrl+U update all  Enter details  ? help  q quit"
	FooterLogs                     = "Esc back  / search  p pause  w wrap  G newest  Enter details  ? help  q quit"
	FooterSubscriptions            = "Esc back  Enter details  a add  e edit  Space toggle  p proxy  r refresh  Ctrl+R refresh all  u use  d delete  ? help  q quit"
	FooterWebGUI                   = "Esc back  ? help  q quit"
	FooterWebGUIActions            = "Esc back  ↑/↓ panel  Space set default  o open  i install  u update  r reinstall  x uninstall  b rollback  ? help  q quit"
	FooterSystem                   = "Esc back  Enter activate  ? help  q quit"
	FooterSearchMode               = "Type to filter  ←/→ cursor  ↑/↓ leave  Esc done  ? help  q quit"
	FooterDetailMode               = "Enter/Esc close  ? help  q quit"
	FooterColumnsMode              = "↑/↓ column  Space toggle  Enter save  Esc cancel  ? help  q quit"
	HelpTitle                      = "Keyboard help"
	HelpBody                       = "Navigation: ↑/↓ select a page on the rail, Enter opens the page, Esc returns to the rail. Arrow keys only navigate inside the open page.\nTab is reserved for forms and dialogs. Press q to quit.\n\nSubscriptions: a add, e edit, Space enable/disable, p cycle proxy mode, r refresh, Ctrl+R refresh all, u activate, d delete, Enter details."
	GlobalStatePendingLabel        = "Working…"
	GlobalStateStaleLabel          = "Daemon disconnected — actions paused"
	GlobalStateCapabilityLostLabel = "Action unavailable in this build"
	GlobalStateReconnectedLabel    = "Reconnected"
	GlobalStateConflictLabel       = "Changed elsewhere — reloaded"
	ConfirmLabel                   = "Confirm"
	CancelLabel                    = "Cancel"
	ObjectLabel                    = "Object"
	ImpactLabel                    = "Impact"
	RollbackLabel                  = "Rollback"
	StaleLabel                     = "Stale"
	// Top-right dual badges: Service (OS) and Daemon (control plane link).
	// Combined as "Service … · Daemon …" via StatusRightJoin.
	StatusServiceNotInstalled = "Service not installed"
	StatusServiceStopped      = "Service stopped"
	StatusServiceRunning      = "Service running"
	StatusServiceUnknown      = "Service unknown"
	StatusDaemonConnected     = "Connected"
	StatusDaemonReconnecting  = "Reconnecting"
	StatusDaemonOffline       = "Offline"
	// Legacy aliases used by older tests / footer copy.
	StatusRightStale               = StatusDaemonOffline
	StatusRightDaemonOffline       = StatusDaemonOffline
	StatusRightReconnecting        = StatusDaemonReconnecting
	StatusRightServiceNotInstalled = StatusServiceNotInstalled
	StatusRightServiceStopped      = StatusServiceStopped
	StatusRightServiceUnknown      = StatusServiceUnknown
	StatusRightJoin                = " · "
	// Overview General section field labels.
	OverviewGeneralTitle  = "General"
	OverviewServiceLabel  = "Service"
	OverviewMihariLabel   = "Mihari"
	OverviewSysProxyLabel = "SysProxy"
	OverviewTunLabel      = "TUN"
	OverviewHealthLabel   = "Health"
	OverviewValueOff      = "off"
	OverviewValueOn       = "on"
	OverviewValueOwned    = "owned"
	OverviewValueForeign  = "foreign"
	OverviewValueDash     = "—"
	// OverviewDriftLabel flags a desired/observed system-proxy drift on the
	// Overview badge (appended as "on · drift") so it matches the System page.
	OverviewDriftLabel = "drift"
	// Section titles are embedded in the top border line (╭─── Name ───╮), not body text.
	MonitorTrafficTitle      = "Traffic · 60 s"
	MonitorMemoryTitle       = "Memory · 60 s"
	MonitorConnectionsLabel  = "Connections"
	MonitorMemoryLabel       = "Memory"
	MonitorMemoryShort       = "MEM"
	MonitorUploadShort       = "UL"
	MonitorDownloadShort     = "DL"
	MonitorUploadTotal       = "Uploaded"
	MonitorDownloadTotal     = "Downloaded"
	UnknownLabel             = "Unknown"
	AvailableLabel           = "Available"
	PIDLabel                 = "PID"
	DesiredLabel             = "Desired"
	ObservedLabel            = "Observed"
	ConfigApplyingLabel      = "Applying changes..."
	ConfigHealthOKLabel      = "All Config Desired and Applied Successfully"
	ConfigFailedLabel        = "Config apply failed"
	CacheMissingLabel        = "Cache missing"
	NoDefaultPanelLabel      = "no default panel"
	NoRecentOperations       = "No operations in this session"
	CoreCardTitle            = "Core"
	SubscriptionCardTitle    = "Subscription"
	WebGUICardTitle          = "Web GUI"
	RecentOperationsTitle    = "Recent operations"
	NoProxyGroups            = "No proxy groups are available."
	MissingValue             = "—"
	TestingLabel             = "Testing…"
	TimeoutLabel             = "Timeout"
	ConnectionsActiveLabel   = "Active"
	ConnectionsClosedLabel   = "Closed"
	SourceIPLabel            = "Source IP"
	SearchPlaceholder        = "Search…"
	ColumnsLabel             = "Columns"
	PauseLabel               = "Pause"
	ResumeLabel              = "Resume"
	ConnectionDetailsTitle   = "Connection details"
	OverviewTabLabel         = "Overview"
	RawTabLabel              = "Raw"
	ProxiesTabLabel          = "Proxies"
	BasicSectionTitle        = "Basic"
	SourceDestinationTitle   = "Source & destination"
	TrafficSectionTitle      = "Traffic"
	OutboundSectionTitle     = "Outbound"
	ChainLabel               = "Chain"
	NoConnections            = "No matching connections."
	ColumnPickerTitle        = "Visible columns"
	SaveLabel                = "Save"
	CloseAllConnectionsTitle = "Close all connections"
	AllActiveConnections     = "All active connections"
	CloseAllImpact           = "Every current connection will be interrupted."
	CloseAllRollback         = "Closed connections cannot be restored."
	GeoIPSectionTitle        = "GeoIP"
	LoadingLabel             = "Loading…"
	// Section card titles (embedded in top border via RenderBorderedSection).
	ControlsSectionTitle = "Controls"
	ProxiesSectionTitle  = "Proxies"
	LogsSectionTitle     = "Logs"
)

const (
	WebGUITitle       = "Web GUI"
	WebGUIUnavailable = "Web GUI status unavailable"
	// WebGUILifecycleUnavailable is neutral copy when the capability is absent (no roadmap phrasing).
	WebGUILifecycleUnavailable = "Web GUI lifecycle is not available in this build."
	ActivePanelLabel           = "Default panel"
	OpenBrowserHint            = "Open selected: o"
	InstallPanelTitle          = "Install panel"
	InstallPanelImpact         = "Downloads and installs the selected panel build."
	InstallPanelRollback       = "Previous builds remain available for rollback when retained."
	UpdatePanelTitle           = "Update panel"
	UpdatePanelImpact          = "Downloads the latest panel build without changing the active pointer until activated."
	UpdatePanelRollback        = "Previous installed builds may remain for rollback."
	ActivatePanelTitle         = "Set default panel"
	ActivatePanelImpact        = "Sets the selected installed panel as the default for root /. Other installed panels stay available at /__mihari/panels/{id}/."
	ActivatePanelRollback      = "Choose another installed panel as default, or open any panel with o."
	RollbackPanelTitle         = "Rollback panel"
	RollbackPanelImpact        = "Restores the previous retained panel build as active."
	RollbackPanelRollback      = "The current build is retained as the next rollback target when possible."
	OpenWebGUITitle            = "Open browser"
	OpenWebGUIImpact           = "Opens the selected panel at its own URL with a one-shot access token. Other installed panels remain usable at different paths."
	OpenWebGUIRollback         = "Close the browser tab; token is not stored by Mihari."
	UninstallPanelTitle        = "Uninstall panel"
	UninstallPanelImpact       = "Deletes all local builds for the selected panel. Other panels stay installed."
	UninstallPanelRollback     = "Reinstall the panel from the catalog (i or r)."
	ReinstallPanelTitle        = "Reinstall panel"
	ReinstallPanelImpact       = "Removes local builds then downloads and installs the latest build again."
	ReinstallPanelRollback     = "Use rollback when a previous build was retained; otherwise reinstall again."
	ActiveLabel                = "Active"
	BrowserSessionsLabel       = "Browser sessions"
	NoWebGUIPanels             = "No Web GUI panels are installed."
	GatewaySafeguardsTitle     = "Gateway safeguards"
	SystemTitle                = "System"
	SystemStateUnavailable     = "System endpoint state unavailable"
	CoreStateUnavailable       = "Core state unavailable"
	SystemChangedMessage       = "System state changed; reloaded current values."
	SystemActionFailed         = "System action failed"
	DaemonSectionTitle         = "Daemon"
	DaemonLabel                = "Daemon"
	// Daemon endpoint rows: proxy/core are informational; panel rows open the
	// browser on Enter (no confirmation, one-shot token stays in Execute).
	ProxyEndpointLabel      = "Proxy endpoint"
	MihomoCoreAPILabel      = "Mihomo Core API"
	ZashboardLabel          = "Zashboard"
	MetaCubeXDLabel         = "MetaCubeXD"
	ProxyEndpointDetail     = "Local mixed HTTP/SOCKS proxy endpoint for client traffic."
	MihomoCoreAPIDetail     = "Mihomo core external controller endpoint (API and dashboard)."
	PanelOpenDetail         = "Web GUI panel mount. Enter opens it in the default browser."
	CoreSectionTitle        = "mihomo core"
	MihomoCoreLabel         = "mihomo core"
	UpdateCoreLabel         = "Update core"
	UpdateMihariLabel       = "Update Mihari"
	InstallCoreLabel        = "Install core"
	RestartCoreLabel        = "Restart core"
	MaintenanceSectionTitle = "Maintenance"
	RunSetupLabel           = "Run Setup"
	RunSetupDetail          = "Open the standalone Setup flow without changing onboarding state until completion."
	NetworkSectionTitle     = "Network"
	TUNLabel                = "TUN"
	SystemProxyLabel        = "System proxy"

	// Row-local short-verb labels for the Network action rows. The status row
	// above (and the Network section) already names the object, so the action
	// row only carries the verb, mirroring coreActionLabel's Install/Update.
	EnableSystemProxyLabel      = "Enable"
	DisableSystemProxyLabel     = "Disable"
	ForceEnableSystemProxyLabel = "Force enable"
	EnableTunLabel              = "Enable"
	DisableTunLabel             = "Disable"

	SystemServiceLabel        = "System service"
	SystemServiceSectionTitle = "System service"
	ServiceStatusLabel        = "Status"
	ServiceInstallLabel       = "Install service"
	ServiceUninstallLabel     = "Uninstall service"
	ServiceReinstallLabel     = "Reinstall service"
	ServiceStartLabel         = "Start service"
	ServiceStopLabel          = "Stop service"
	ServiceRestartLabel       = "Restart service"
	ServiceNeedsElevation     = "Needs admin"
	ServiceElevationRequired  = "Administrator privileges are required; re-run Mihari from an elevated shell."
	ServiceActionFailed       = "Service action failed"
	ServiceStatusUnavailable  = "Service status unavailable"
	ServiceInstallTitle       = "Install OS service"
	ServiceUninstallTitle     = "Uninstall OS service"
	ServiceReinstallTitle     = "Reinstall OS service"
	ServiceStartTitle         = "Start OS service"
	ServiceStopTitle          = "Stop OS service"
	ServiceRestartTitle       = "Restart OS service"
	ServiceInstallImpact      = "Copies this mihari binary into the machine install directory, then registers a native OS service that runs that installed copy (not the download folder)."
	ServiceUninstallImpact    = "Removes the OS service registration. The running daemon may stop and the TUI control connection can disconnect. Installed files under the install directory are left in place."
	ServiceReinstallImpact    = "Stops the service, copies this binary into the install directory, re-registers ImagePath to that install path, and starts the service. Use after upgrading."
	ServiceStartImpact        = "Starts the OS-managed Mihari daemon service."
	ServiceStopImpact         = "Stops the OS service. The local control connection will disconnect if this TUI is talking to that daemon."
	ServiceRestartImpact      = "Restarts the OS service. The local control connection may disconnect briefly while the daemon comes back."
	ServiceInstallRollback    = "Use Uninstall service to remove the registration."
	ServiceUninstallRollback  = "Use Install service to register again."
	ServiceReinstallRollback  = "Reinstall again from a known-good binary if the new registration fails."
	ServiceStartRollback      = "Use Stop service to stop it again."
	ServiceStopRollback       = "Use Start service to start it again."
	ServiceRestartRollback    = "Service returns to the prior running state when restart succeeds."
	// In-row progress notes (paired with braille spinner on System).
	ServiceProgressInstalling   = "Installing"
	ServiceProgressUninstalling = "Uninstalling"
	ServiceProgressReinstalling = "Reinstalling"
	ServiceProgressStarting     = "Starting"
	ServiceProgressStopping     = "Stopping"
	ServiceProgressRestarting   = "Restarting"
	CoreProgressUpdating        = "Updating"
	CoreProgressInstalling      = "Installing"
	CoreProgressRestarting      = "Restarting"
	MihariProgressChecking      = "Checking"
	MihariProgressUpdating      = "Updating"
	ProxyProgressEnabling       = "Enabling"
	ProxyProgressDisabling      = "Disabling"
	TunProgressEnabling         = "Enabling"
	TunProgressDisabling        = "Disabling"
	// Sticky row outcome badges after a System action finishes (until page leave / re-run).
	DoneLabel   = "Done"
	FailedLabel = "Failed"
	// SucceededLabel/FailedLabel are the Recent operations ledger states. "Succeeded"
	// is a dedicated word (not Done): ClassifyStatusTone matches it exactly as
	// Positive, while "Done" falls through to the neutral substring fallback.
	SucceededLabel               = "Succeeded"
	ServiceElevatedLabel         = "elevated"
	ServiceNotElevatedLabel      = "not elevated"
	TUNUnavailableDetail         = "TUN management is unavailable in this build."
	ServiceUnavailableDetail     = "System-service management is unavailable in this build."
	SystemProxyUnavailableDetail = "System proxy management is unavailable in this build."
	EnableSystemProxyTitle       = "Enable system proxy"
	EnableSystemProxyImpact      = "Routes browser and system HTTP(S) traffic through Mihari's mixed port."
	EnableSystemProxyRollback    = "Disable system proxy to clear Mihari-owned settings."
	ForceSystemProxyTitle        = "Overwrite system proxy"
	ForceSystemProxyImpact       = "Current system proxy is %s; overwrite with Mihari target %s?"
	ForceSystemProxyRollback     = "Previous non-Mihari proxy settings will not be restored automatically."
	DisableSystemProxyTitle      = "Disable system proxy"
	DisableSystemProxyImpact     = "Clears Mihari-owned system proxy settings on this machine."
	DisableSystemProxyRollback   = "Enable system proxy again to restore Mihari's target."
	SystemProxyNotOwnedMessage   = "System proxy is managed by another application; Mihari will not clear it."
	SystemProxyActionFailed      = "System proxy action failed"
	SystemProxyStateUnavailable  = "System proxy state unavailable"
	EnableTunTitle               = "Enable TUN"
	EnableTunImpact              = "Routes device traffic through mihomo TUN. May require elevated privileges or the OS service."
	EnableTunRollback            = "Disable TUN to return to the previous managed state."
	DisableTunTitle              = "Disable TUN"
	DisableTunImpact             = "Turns off managed TUN mode in mihomo."
	DisableTunRollback           = "Enable TUN again to restore managed TUN."
	TunActionFailed              = "TUN action failed"
	ForceTunTitle                = "Overwrite TUN despite detected conflict"
	ForceTunImpactAB             = "Detected %d other TUN interface(s) [%s] and %d other mihomo process(es); another mihomo may also have TUN on. Route conflict / loop risk."
	ForceTunImpactA              = "Detected %d other TUN interface(s) [%s]; likely from other proxy software. Route conflict risk."
	ForceTunRollback             = "Other TUN interfaces will not be closed automatically."
	TunConflictLabelAB           = "Conflict · %d TUN + %d mihomo"
	TunConflictLabelA            = "Conflict · %d TUN"
	TunConflictLabelB            = "%d other mihomo"
	TunStateUnavailable          = "TUN state unavailable"
	OwnedLabel                   = "owned"
	ForeignLabel                 = "foreign"
	LiveLabel                    = "Live"
	UnmanagedLabel               = "unmanaged"
	UpdateCoreTitle              = "Update mihomo core"
	UpdateMihariTitle            = "Update Mihari"
	UpdateMihariImpact           = "The Mihari binary will be replaced, the installed service will be restarted, and this terminal will enter the updated TUI."
	UpdateMihariRollback         = "The current TUI stays open if replacement does not complete."
	UpdateMihariUpToDate         = "Up to date"
	UpdateMihariAvailable        = "available"
	UpdateMihariCheckFailed      = "Mihari version check failed"
	UpdateMihariActionFailed     = "Mihari update failed"
	InstallCoreTitle             = "Install mihomo core"
	InstallCoreImpact            = "A validated mihomo core will be installed under daemon ownership."
	UpdateCoreImpact             = "A validated core build will replace the active binary."
	UpdateCoreRollback           = "The installer retains the previous valid binary when replacement fails."
	RestartCoreTitle             = "Restart mihomo core"
	RestartCoreImpact            = "Current proxy connections may be interrupted."
	RestartCoreRollback          = "The supervised core will retry according to daemon policy."
)

const (
	SetupTitle                      = "Setup"
	SetupProgress                   = "Step %d of %d"
	SetupUnavailable                = "Setup state is unavailable"
	SetupActionFailed               = "Setup action failed"
	SetupChangedMessage             = "State changed; reloaded current setup values."
	SetupCompletionFailed           = "Setup could not be completed"
	LocalEndpointsLabel             = "Local endpoints"
	SetupEndpointHelp               = "Tab/Shift+Tab fields  Enter continue or auto-fix  Esc back"
	SetupPortInUse                  = "✗ in use"
	SetupPortAutoFixHint            = "检测到端口占用，已自动切换到可用端口，再次 Enter 继续。"
	SetupCoreTitle                  = "mihomo core"
	SetupCoreBody                   = "Install or verify the daemon-owned mihomo core."
	SetupCoreLocalReady             = "Local core %s detected — will be reused, no download needed."
	SetupCoreWillDownload           = "No usable local core — Enter downloads and installs it."
	SetupEnterInstall               = "Enter install  Esc back"
	SetupSubscriptionTitle          = "Subscription (optional)"
	SetupSubscriptionBody           = "Add an initial subscription, or leave both fields blank."
	SetupSubscriptionHelp           = "Enter add/skip empty form  Tab fields  Esc back"
	SetupGeoIPTitle                 = "Local GeoIP databases"
	SetupGeoIPBody                  = "Prepare Country and ASN databases for local connection details."
	SetupGeoIPLocalReady            = "Local Country/ASN databases detected — will be reused, no download needed."
	SetupGeoIPWillDownload          = "No usable local databases — Enter downloads them."
	SetupEnterOrSkip                = "Enter continue  s skip  Esc back"
	SetupReviewTitle                = "Review"
	SetupReviewCoreLocal            = "本地已有"
	SetupReviewCoreFresh            = "新装"
	SetupReviewCoreFailed           = "安装失败"
	SetupReviewSubscriptionNone     = "未添加（已跳过）"
	SetupReviewGeoIPReady           = "Country ✓  ASN ✓"
	SetupReviewGeoIPSkipped         = "已跳过"
	SetupReviewGeoIPFailed          = "更新失败"
	SetupReviewRestartRequired      = "（需重启生效）"
	SetupReviewServiceUnknown       = "未知"
	SetupReviewServiceNotRegistered = "未注册为开机自启"
	SetupCompleteHelp               = "Enter complete setup  Esc back"
	SetupFooter                     = "Tab fields  Enter continue  Esc back  Ctrl+C quit"
	ReplaceConfigurationTitle       = "Replace effective configuration"
	ReplaceConfigurationImpact      = "Endpoint changes are saved by the daemon and require a restart."
	ReplaceConfigurationRollback    = "The previous settings remain recoverable only until the new settings are accepted."
	RestartRequiredTitle            = "Restart required"
	RestartRequiredBody             = "Endpoint changes are saved. Restart the Mihari daemon to apply them."
)

const (
	RulesTabLabel              = "Rules"
	RuleProvidersTabLabel      = "Providers"
	TypeLabel                  = "Type"
	TargetLabel                = "Target"
	BehaviorLabel              = "Behavior"
	FormatLabel                = "Format"
	RulesCountLabel            = "Rules"
	UpdatedLabel               = "Updated"
	StatusLabel                = "Status"
	NameLabel                  = "Name"
	PayloadLabel               = "Payload"
	EvaluationOrderLabel       = "Evaluation order"
	FilterAllLabel             = "All"
	PendingLabel               = "Pending"
	RulesUnavailable           = "Rules unavailable"
	RuleProvidersUnavailable   = "Providers unavailable"
	ProviderUpdateFailed       = "Provider update failed"
	NoMatchingRules            = "No matching rules."
	NoMatchingRuleProviders    = "No matching rule providers."
	RuleDetailsTitle           = "Rule details"
	RuleProviderDetailsTitle   = "Rule provider details"
	UpdateAllProvidersTitle    = "Update all rule providers"
	AllRuleProviders           = "All rule providers"
	UpdateAllProvidersImpact   = "Each provider will be refreshed in sequence."
	UpdateAllProvidersRollback = "Existing provider data remains available if an update fails."
	EscCloseHint               = "Esc close"
)

const (
	LevelLabel      = "Level"
	WrapLabel       = "Wrap"
	UnreadLabel     = "Unread"
	DroppedLabel    = "Dropped"
	TimeLabel       = "Time"
	MessageLabel    = "Message"
	NoMatchingLogs  = "No matching logs."
	LogDetailsTitle = "Log details"
	OnLabel         = "On"
	OffLabel        = "Off"
)

const (
	SubscriptionsTitle = "Subscriptions"
	EnabledLabel       = "Enabled"
	DisabledLabel      = "Disabled"
	// Load-phase labels: only "Live" means the active profile was applied to mihomo.
	// Intermediate states cover cache/catalog progress before the core can use it.
	LoadLiveState     = "Live"
	LoadCachedState   = "Cached"
	LoadMissingState  = "Missing"
	LoadStaleState    = "Stale"
	LoadFailedState   = "Failed"
	LoadFetchingLabel = "Fetching"
	LoadApplyingLabel = "Applying"
	LoadWorkingLabel  = "Working"
	// Legacy aliases kept for older tests / call sites.
	CacheReadyState                 = LoadLiveState
	CacheMissingState               = LoadMissingState
	CacheStaleState                 = LoadStaleState
	CacheUpdatingState              = LoadFetchingLabel
	ManualLabel                     = "Manual"
	RetryPendingLabel               = "Retry pending"
	NoSubscriptions                 = "No subscriptions are configured."
	SubscriptionChangedMessage      = "Subscription changed; reloaded current state."
	SubscriptionOperationFailed     = "Subscription operation failed"
	SubscriptionsUnavailable        = "Subscriptions unavailable"
	RemoveSubscriptionTitle         = "Remove subscription"
	RemoveSubscriptionImpact        = "The subscription and its cached profile will be removed."
	RemoveSubscriptionRollback      = "The removed subscription cannot be restored automatically."
	RefreshAllSubscriptionsTitle    = "Refresh all subscriptions"
	AllSubscriptionsLabel           = "All subscriptions"
	RefreshAllSubscriptionsImpact   = "Each subscription will be refreshed in sequence."
	RefreshAllSubscriptionsRollback = "Existing caches remain available if a refresh fails."
	AddSubscriptionTitle            = "Add subscription"
	EditSubscriptionTitle           = "Edit subscription"
	SubscriptionDetailsTitle        = "Subscription details"
	FormHelp                        = "Tab/Shift+Tab fields  Enter next/save  Esc cancel"
	DetailCloseHelp                 = "Enter/Esc close"
	InvalidSubscriptionForm         = "Complete the required fields with valid values."
	AutoRefreshLabel                = "Auto refresh"
	CacheLabel                      = "Cache"
	LoadLabel                       = "Load"
	IntervalLabel                   = "Interval"
	GlobalLabel                     = "Global"
	LastUpdateLabel                 = "Last update"
	NextUpdateLabel                 = "Next update"
	TrafficLabel                    = "Traffic"
	LastErrorLabel                  = "Last error"
)

// FocusMarker is the keyboard-focus glyph for list/table rows and form fields (U+203A + space).
const FocusMarker = "› "

var connectionColumnLabels = map[string]string{
	"host": "Host", "network": "Network", "source": "Source", "destination": "Destination",
	"chain": "Chain", "rule": "Rule", "process": "Process", "upload": "Upload",
	"download": "Download", "traffic": "Traffic", "start": "Start",
}

func ConnectionColumnLabel(id string) string {
	if label := connectionColumnLabels[id]; label != "" {
		return label
	}
	return id
}

var pageLabels = map[PageID]string{
	PageOverview:      "Overview",
	PageProxies:       "Proxies",
	PageConnections:   "Conns",
	PageRules:         "Rules",
	PageLogs:          "Logs",
	PageSubscriptions: "Subs",
	PageWebGUI:        "Web GUI",
	PageSystem:        "System",
	PageSetup:         "Setup",
}

func PageLabel(id PageID) string {
	if label := pageLabels[id]; label != "" {
		return label
	}
	return string(id)
}
