package ui

const (
	AppName                        = "Mihari"
	Connecting                     = "Connecting to the Mihari daemon…"
	ResizeRequired                 = "Terminal too small"
	ResizeInstructions             = "Resize to at least 72×22. Press ? for help or q to quit."
	UnavailableTitle               = "Unavailable"
	UnavailableReason              = "This page is waiting for daemon capability support."
	ConfigNotAppliedLabel          = "Not applied"
	NoActiveSubscriptionLabel      = "No active subscription"
	NoSubscriptionsConfiguredLabel = "None configured"
	FooterRail                     = "↑/↓ page  Enter/→ open  ? help  q quit"
	FooterContent                  = "← navigation  ? help  q quit"
	FooterOverview                 = "← back  ? help  q quit"
	FooterProxies                  = "← back  Enter expand  t test  Ctrl+T test all  ? help  q quit"
	FooterConnections              = "← back  / search  x close  p pause  Enter details  ? help  q quit"
	FooterRules                    = "← back  / search  r reload  u update  Ctrl+U update all  Enter details  ? help  q quit"
	FooterLogs                     = "← back  / search  p pause  w wrap  G newest  Enter details  ? help  q quit"
	FooterSubscriptions            = "← back  Enter details  a add  e edit  Space toggle  r refresh  Ctrl+R refresh all  u use  d delete  ? help  q quit"
	FooterWebGUI                   = "← back  ? help  q quit"
	FooterWebGUIActions            = "← back  ↑/↓ panel  Space activate  o open  i install  u update  b rollback  ? help  q quit"
	FooterSystem                   = "← back  Enter activate  ? help  q quit"
	FooterSearchMode               = "Type to filter  Enter/Esc done  ? help  q quit"
	FooterDetailMode               = "Enter/Esc close  ? help  q quit"
	FooterColumnsMode              = "↑/↓ column  Space toggle  Enter save  Esc cancel  ? help  q quit"
	HelpTitle                      = "Keyboard help"
	HelpBody                       = "Navigation: ↑/↓ select a page, Enter or → enters content, ← returns when available.\nTab is reserved for forms and dialogs. Press q to quit.\n\nSubscriptions: a add, e edit, Space enable/disable, r refresh, Ctrl+R refresh all, u activate, d delete, Enter details."
	GlobalStatePendingLabel        = "Working…"
	GlobalStateStaleLabel          = "Daemon disconnected — actions paused"
	GlobalStateCapabilityLostLabel = "Action unavailable in this build"
	GlobalStateReconnectedLabel    = "Reconnected"
	GlobalStateConflictLabel       = "Changed elsewhere — reloaded"
	ConfirmLabel                   = "Confirm"
	CancelLabel                    = "Cancel"
	ObjectLabel                    = "Object"
	ImpactLabel                    = "Impact"
	RollbackLabel                  = "Rollback"
	StaleLabel                     = "Stale"
	MonitorTrafficTitle            = "Traffic · 60 s"
	MonitorMemoryTitle             = "Memory · 60 s"
	MonitorConnectionsLabel        = "Connections"
	MonitorMemoryLabel             = "Memory"
	MonitorMemoryShort             = "MEM"
	MonitorUploadShort             = "UL"
	MonitorDownloadShort           = "DL"
	MonitorUploadTotal             = "Uploaded"
	MonitorDownloadTotal           = "Downloaded"
	UnknownLabel                   = "Unknown"
	AvailableLabel                 = "Available"
	PIDLabel                       = "PID"
	DesiredLabel                   = "Desired"
	ObservedLabel                  = "Observed"
	CacheMissingLabel              = "Cache missing"
	NoRecentOperations             = "No operations in this session"
	CoreCardTitle                  = "Core"
	ConfigCardTitle                = "Config"
	SubscriptionCardTitle          = "Subscription"
	WebGUICardTitle                = "Web GUI"
	RecentOperationsTitle          = "Recent operations"
	NoProxyGroups                  = "No proxy groups are available."
	MissingValue                   = "—"
	TestingLabel                   = "Testing…"
	TimeoutLabel                   = "Timeout"
	ConnectionsActiveLabel         = "Active"
	ConnectionsClosedLabel         = "Closed"
	SourceIPLabel                  = "Source IP"
	SearchPlaceholder              = "Search…"
	ColumnsLabel                   = "Columns"
	PauseLabel                     = "Pause"
	ResumeLabel                    = "Resume"
	ConnectionDetailsTitle         = "Connection details"
	OverviewTabLabel               = "Overview"
	RawTabLabel                    = "Raw"
	ProxiesTabLabel                = "Proxies"
	BasicSectionTitle              = "Basic"
	SourceDestinationTitle         = "Source & destination"
	TrafficSectionTitle            = "Traffic"
	OutboundSectionTitle           = "Outbound"
	ChainLabel                     = "Chain"
	NoConnections                  = "No matching connections."
	ColumnPickerTitle              = "Visible columns"
	SaveLabel                      = "Save"
	CloseAllConnectionsTitle       = "Close all connections"
	AllActiveConnections           = "All active connections"
	CloseAllImpact                 = "Every current connection will be interrupted."
	CloseAllRollback               = "Closed connections cannot be restored."
	GeoIPSectionTitle              = "GeoIP"
	LoadingLabel                   = "Loading…"
)

const (
	WebGUITitle       = "Web GUI"
	WebGUIUnavailable = "Web GUI status unavailable"
	// WebGUILifecycleUnavailable is neutral copy when the capability is absent (no roadmap phrasing).
	WebGUILifecycleUnavailable = "Web GUI lifecycle is not available in this build."
	ActivePanelLabel           = "Active panel"
	OpenBrowserHint            = "Open Browser: o"
	InstallPanelTitle          = "Install panel"
	InstallPanelImpact         = "Downloads and installs the selected panel build."
	InstallPanelRollback       = "Previous builds remain available for rollback when retained."
	UpdatePanelTitle           = "Update panel"
	UpdatePanelImpact          = "Downloads the latest panel build without changing the active pointer until activated."
	UpdatePanelRollback        = "Previous installed builds may remain for rollback."
	ActivatePanelTitle         = "Activate panel"
	ActivatePanelImpact        = "Switches the Web gateway to the selected installed panel."
	ActivatePanelRollback      = "Use rollback to restore the previous build when retained."
	RollbackPanelTitle         = "Rollback panel"
	RollbackPanelImpact        = "Restores the previous retained panel build as active."
	RollbackPanelRollback      = "The current build is retained as the next rollback target when possible."
	OpenWebGUITitle            = "Open browser"
	OpenWebGUIImpact           = "Opens the local Web GUI with a one-shot access token."
	OpenWebGUIRollback         = "Close the browser tab; token is not stored by Mihari."
	ActiveLabel                = "Active"
	BrowserSessionsLabel       = "Browser sessions"
	NoWebGUIPanels             = "No Web GUI panels are installed."
	GatewaySafeguardsTitle     = "Gateway safeguards"
	SystemTitle                = "System"
	SystemStateUnavailable     = "System endpoint state unavailable"
	CoreStateUnavailable       = "Core state unavailable"
	SystemChangedMessage       = "System state changed; reloaded current values."
	SystemActionFailed         = "System action failed"
	DaemonSectionTitle         = "Daemon"
	DaemonLabel                = "Daemon"
	CoreSectionTitle           = "mihomo core"
	MihomoCoreLabel            = "mihomo core"
	UpdateCoreLabel            = "Update core"
	InstallCoreLabel           = "Install core"
	RestartCoreLabel           = "Restart core"
	MaintenanceSectionTitle    = "Maintenance"
	RunSetupLabel              = "Run Setup"
	RunSetupDetail             = "Open the standalone Setup flow without changing onboarding state until completion."
	FutureCapabilitiesTitle    = "Future capabilities"
	TUNLabel                   = "TUN"
	SystemServiceLabel         = "System service"
	TUNUnavailableDetail       = "TUN management is unavailable in this build."
	ServiceUnavailableDetail   = "System-service management is unavailable in this build."
	UpdateCoreTitle            = "Update mihomo core"
	InstallCoreTitle           = "Install mihomo core"
	InstallCoreImpact          = "A validated mihomo core will be installed under daemon ownership."
	UpdateCoreImpact           = "A validated core build will replace the active binary."
	UpdateCoreRollback         = "The installer retains the previous valid binary when replacement fails."
	RestartCoreTitle           = "Restart mihomo core"
	RestartCoreImpact          = "Current proxy connections may be interrupted."
	RestartCoreRollback        = "The supervised core will retry according to daemon policy."
)

const (
	SetupTitle                   = "Setup"
	SetupProgress                = "Step %d of %d"
	SetupUnavailable             = "Setup state is unavailable"
	SetupActionFailed            = "Setup action failed"
	SetupChangedMessage          = "State changed; reloaded current setup values."
	SetupCompletionFailed        = "Setup could not be completed"
	LocalEndpointsLabel          = "Local endpoints"
	SetupEndpointHelp            = "Tab/Shift+Tab fields  Enter continue  Esc back"
	SetupCoreTitle               = "mihomo core"
	SetupCoreBody                = "Install or verify the daemon-owned mihomo core."
	SetupEnterInstall            = "Enter install  Esc back"
	SetupSubscriptionTitle       = "Subscription (optional)"
	SetupSubscriptionBody        = "Add an initial subscription, or leave both fields blank."
	SetupSubscriptionHelp        = "Enter add/skip empty form  Tab fields  Esc back"
	SetupGeoIPTitle              = "Local GeoIP databases"
	SetupGeoIPBody               = "Prepare Country and ASN databases for local connection details."
	SetupEnterOrSkip             = "Enter continue  s skip  Esc back"
	SetupReviewTitle             = "Review"
	SetupWebGUIUnavailable       = "Web GUI: Unavailable in this build (does not block setup)"
	SetupCompleteHelp            = "Enter complete setup  Esc back"
	SetupFooter                  = "Tab fields  Enter continue  Esc back  Ctrl+C quit"
	ReplaceConfigurationTitle    = "Replace effective configuration"
	ReplaceConfigurationImpact   = "Endpoint changes are saved by the daemon and require a restart."
	ReplaceConfigurationRollback = "The previous settings remain recoverable only until the new settings are accepted."
	RestartRequiredTitle         = "Restart required"
	RestartRequiredBody          = "Endpoint changes are saved. Restart the Mihari daemon to apply them."
)

const (
	RulesTabLabel              = "Rules"
	RuleProvidersTabLabel      = "Providers"
	TypeLabel                  = "Type"
	TargetLabel                = "Target"
	BehaviorLabel              = "Behavior"
	FormatLabel                = "Format"
	RulesCountLabel            = "Rules"
	UpdatedLabel               = "Updated"
	StatusLabel                = "Status"
	NameLabel                  = "Name"
	PayloadLabel               = "Payload"
	EvaluationOrderLabel       = "Evaluation order"
	FilterAllLabel             = "All"
	PendingLabel               = "Pending"
	RulesUnavailable           = "Rules unavailable"
	RuleProvidersUnavailable   = "Providers unavailable"
	ProviderUpdateFailed       = "Provider update failed"
	NoMatchingRules            = "No matching rules."
	NoMatchingRuleProviders    = "No matching rule providers."
	RuleDetailsTitle           = "Rule details"
	RuleProviderDetailsTitle   = "Rule provider details"
	UpdateAllProvidersTitle    = "Update all rule providers"
	AllRuleProviders           = "All rule providers"
	UpdateAllProvidersImpact   = "Each provider will be refreshed in sequence."
	UpdateAllProvidersRollback = "Existing provider data remains available if an update fails."
	EscCloseHint               = "Esc close"
)

const (
	LevelLabel      = "Level"
	WrapLabel       = "Wrap"
	UnreadLabel     = "Unread"
	DroppedLabel    = "Dropped"
	TimeLabel       = "Time"
	MessageLabel    = "Message"
	NoMatchingLogs  = "No matching logs."
	LogDetailsTitle = "Log details"
	OnLabel         = "On"
	OffLabel        = "Off"
)

const (
	SubscriptionsTitle              = "Subscriptions"
	EnabledLabel                    = "Enabled"
	DisabledLabel                   = "Disabled"
	CacheReadyState                 = "Ready"
	CacheMissingState               = "Missing"
	CacheStaleState                 = "Stale"
	CacheUpdatingState              = "Updating"
	ManualLabel                     = "Manual"
	RetryPendingLabel               = "Retry pending"
	NoSubscriptions                 = "No subscriptions are configured."
	SubscriptionChangedMessage      = "Subscription changed; reloaded current state."
	SubscriptionOperationFailed     = "Subscription operation failed"
	SubscriptionsUnavailable        = "Subscriptions unavailable"
	RemoveSubscriptionTitle         = "Remove subscription"
	RemoveSubscriptionImpact        = "The subscription and its cached profile will be removed."
	RemoveSubscriptionRollback      = "The removed subscription cannot be restored automatically."
	RefreshAllSubscriptionsTitle    = "Refresh all subscriptions"
	AllSubscriptionsLabel           = "All subscriptions"
	RefreshAllSubscriptionsImpact   = "Each subscription will be refreshed in sequence."
	RefreshAllSubscriptionsRollback = "Existing caches remain available if a refresh fails."
	AddSubscriptionTitle            = "Add subscription"
	EditSubscriptionTitle           = "Edit subscription"
	SubscriptionDetailsTitle        = "Subscription details"
	FormHelp                        = "Tab/Shift+Tab fields  Enter next/save  Esc cancel"
	DetailCloseHelp                 = "Enter/Esc close"
	InvalidSubscriptionForm         = "Complete the required fields with valid values."
	AutoRefreshLabel                = "Auto refresh"
	CacheLabel                      = "Cache"
	IntervalLabel                   = "Interval"
	GlobalLabel                     = "Global"
	LastUpdateLabel                 = "Last update"
	NextUpdateLabel                 = "Next update"
	LastErrorLabel                  = "Last error"
)

// FocusMarker is the keyboard-focus glyph for list/table rows and form fields (U+203A + space).
const FocusMarker = "› "

var connectionColumnLabels = map[string]string{
	"host": "Host", "network": "Network", "source": "Source", "destination": "Destination",
	"chain": "Chain", "rule": "Rule", "process": "Process", "upload": "Upload",
	"download": "Download", "traffic": "Traffic", "start": "Start",
}

func ConnectionColumnLabel(id string) string {
	if label := connectionColumnLabels[id]; label != "" {
		return label
	}
	return id
}

var pageLabels = map[PageID]string{
	PageOverview:      "Overview",
	PageProxies:       "Proxies",
	PageConnections:   "Connections",
	PageRules:         "Rules",
	PageLogs:          "Logs",
	PageSubscriptions: "Subscriptions",
	PageWebGUI:        "Web GUI",
	PageSystem:        "System",
	PageSetup:         "Setup",
}

func PageLabel(id PageID) string {
	if label := pageLabels[id]; label != "" {
		return label
	}
	return string(id)
}
