package subscription

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"os"
	"reflect"

	"github.com/mihari-proxy/mihari/internal/control/protocol"
)

const resourceJournalPath = "staging/providers/activation.json"

type resourceEntry struct {
	Transaction    string            `json:"transaction"`
	SubscriptionID string            `json:"subscription_id"`
	Generation     uint64            `json:"generation"`
	Kind           string            `json:"kind"`
	Name           string            `json:"name"`
	Resource       string            `json:"resource"`
	Format         string            `json:"format"`
	Geo            GeoResourceKind   `json:"geo"`
	Configuration  bool              `json:"configuration"`
	StateRole      resourceStateRole `json:"state_role"`
	Old            providerObject    `json:"old"`
	New            providerObject    `json:"new"`
	Marker         providerObject    `json:"marker"`
	BackupIntent   bool              `json:"backup_intent"`
	BackupDone     bool              `json:"backup_done"`
	SwapIntent     bool              `json:"swap_intent"`
	SwapDone       bool              `json:"swap_done"`
	RestoreIntent  bool              `json:"restore_intent"`
	RestoreDone    bool              `json:"restore_done"`
}
type resourceJournal struct {
	Schema  string          `json:"schema"`
	Done    bool            `json:"done"`
	Entries []resourceEntry `json:"entries"`
}

// ResourceActivation retains the whole fixed-resource rollback set. Its caller
// owns stopped-core execution and Manager activation ownership until settlement.
// The store gate is acquired only for short filesystem operations, never -t.
type ResourceActivation struct {
	prepared      *PreparedResources
	journal       resourceJournal
	storePath     string
	storeIdentity string
	settled       bool
	committed     bool
}

// StoreBinding identifies the sealed data root that owns this activation. It
// conveys no path operation or callback authority.
func (a *ResourceActivation) StoreBinding() (string, string, error) {
	if a == nil || a.prepared == nil || a.storePath == "" || a.storeIdentity == "" {
		return "", "", dataError("resource activation unavailable")
	}
	return a.storePath, a.storeIdentity, nil
}

func (e resourceEntry) target() (string, error) {
	if e.StateRole != "" {
		if e.Configuration || e.Geo != "" || e.Generation != 0 || e.Kind != "" || e.Name != "" || e.Resource != "" || e.Format != "" {
			return "", dataError("invalid activation state identity")
		}
		return stateTarget(e.StateRole, e.SubscriptionID)
	}
	if e.Configuration {
		if e.Geo != "" || e.SubscriptionID != "" || e.Generation != 0 || e.Kind != "" || e.Name != "" || e.Resource != "" || e.Format != "" {
			return "", dataError("invalid configuration activation identity")
		}
		return "runtime/config.yaml", nil
	}
	if e.Geo != "" {
		if e.SubscriptionID != "" || e.Generation != 0 || e.Kind != "" || e.Name != "" || e.Resource != "" || e.Format != "" {
			return "", dataError("invalid Geo activation identity")
		}
		name, err := GeoResourcePath(e.Geo)
		return "runtime/core-home/" + name, err
	}
	return providerTarget(ProviderSpec{SubscriptionID: e.SubscriptionID, Generation: e.Generation, Kind: e.Kind, Name: e.Name, ResourceID: e.Resource, Format: e.Format})
}

// ValidationConfig returns a copy of the policy-generated bytes and their
// fixed data-root binding. Core uses this typed activation to validate the
// exact candidate against the already-swapped fixed resource home.
func (a *ResourceActivation) ValidationConfig(ctx context.Context) ([]byte, [32]byte, string, string, error) {
	var zero [32]byte
	if a == nil || a.prepared == nil {
		return nil, zero, "", "", dataError("resource activation unavailable")
	}
	s := a.prepared.store
	release, err := s.acquire(ctx)
	if err != nil {
		return nil, zero, "", "", err
	}
	defer release()
	if a.settled {
		return nil, zero, "", "", dataError("resource activation settled")
	}
	if err = a.recheck(ctx); err != nil {
		return nil, zero, "", "", err
	}
	_, entry, err := a.configEntry()
	if err != nil {
		return nil, zero, "", "", err
	}
	b, err := s.files.read(ctx, entry.candidatePath(), 32<<20)
	if err != nil {
		return nil, zero, "", "", err
	}
	hash := sha256.Sum256(b)
	if hex.EncodeToString(hash[:]) != entry.New.SHA256 {
		return nil, zero, "", "", providerConflict()
	}
	return b, hash, a.storePath, a.storeIdentity, nil
}

// PublishConfig publishes only the policy-generated final WAL entry. Core
// calls this after validating the exact hash under its execution capability.
func (a *ResourceActivation) PublishConfig(ctx context.Context, expected [32]byte) error {
	if a == nil || a.prepared == nil {
		return dataError("resource activation unavailable")
	}
	s := a.prepared.store
	release, err := s.acquire(ctx)
	if err != nil {
		return err
	}
	defer release()
	if a.settled {
		return dataError("resource activation settled")
	}
	if err = a.recheck(ctx); err != nil {
		return err
	}
	index, entry, err := a.configEntry()
	if err != nil {
		return err
	}
	if entry.SwapIntent || entry.SwapDone || hex.EncodeToString(expected[:]) != entry.New.SHA256 {
		return dataError("validated configuration does not match activation")
	}
	b, err := s.files.read(ctx, entry.candidatePath(), 32<<20)
	if err != nil {
		return err
	}
	if sha256.Sum256(b) != expected {
		return providerConflict()
	}
	if err = a.swap(ctx, index); err != nil {
		return err
	}
	return a.recheck(ctx)
}

func (a *ResourceActivation) configEntry() (int, resourceEntry, error) {
	index := -1
	var result resourceEntry
	for i, entry := range a.journal.Entries {
		if !entry.Configuration {
			continue
		}
		if index >= 0 {
			return -1, resourceEntry{}, dataError("duplicate activation configuration")
		}
		index, result = i, entry
	}
	if index < 0 {
		return -1, resourceEntry{}, dataError("activation configuration unavailable")
	}
	return index, result, nil
}
func (e resourceEntry) candidatePath() string {
	return "staging/providers/" + e.Transaction + "/candidate"
}
func (e resourceEntry) markerPath() string {
	return "staging/providers/" + e.Transaction + "/transaction-id"
}
func (e resourceEntry) backupPath() string { p, _ := e.target(); return p + ".old-" + e.Transaction }

// Activate atomically owns the prepared set and journals every old/new rename.
// No running core or validator may use H until Finish or Restore converges.
func (p *PreparedResources) Activate(ctx context.Context) (*ResourceActivation, error) {
	if err := p.Recheck(ctx); err != nil {
		return nil, err
	}
	s := p.store
	release, err := s.acquire(ctx)
	if err != nil {
		return nil, err
	}
	defer release()
	if err = s.noPending(ctx); err != nil {
		return nil, err
	}
	storePath, storeIdentity := s.files.storeBinding()
	if storePath == "" || storeIdentity == "" || p.configuration == nil {
		return nil, dataError("resource activation binding unavailable")
	}
	a := &ResourceActivation{prepared: p, storePath: storePath, storeIdentity: storeIdentity, journal: resourceJournal{Schema: "mihari.resource-activation/v1", Entries: []resourceEntry{}}}
	seen := map[string]bool{}
	for _, group := range [][]*PreparedProvider{p.providers, p.geo, []*PreparedProvider{p.configuration}, p.state} {
		for _, c := range group {
			if c.closed {
				return nil, dataError("resource candidate closed")
			}
			spec := c.spec
			e := resourceEntry{Transaction: c.transaction, SubscriptionID: spec.SubscriptionID, Generation: spec.Generation, Kind: spec.Kind, Name: spec.Name, Resource: spec.ResourceID, Format: spec.Format, Geo: c.geo, Configuration: c.configuration, StateRole: c.stateRole, Old: c.old, New: c.candidate, Marker: c.marker}
			path, e2 := e.target()
			if e2 != nil {
				return nil, e2
			}
			if seen[path] {
				return nil, dataError("duplicate activation resource")
			}
			seen[path] = true
			for path, want := range map[string]providerObject{path: e.Old, e.candidatePath(): e.New, e.markerPath(): e.Marker, e.backupPath(): {}} {
				got, e2 := s.files.inspect(ctx, path)
				if e2 != nil {
					return nil, e2
				}
				if got != want {
					return nil, providerConflict()
				}
			}
			a.journal.Entries = append(a.journal.Entries, e)
		}
	}
	if len(a.journal.Entries) == 0 {
		return a, nil
	}
	// Every identity is durable before the first target changes. Moving the old
	// inode to a same-parent backup avoids copying large Geo bytes under mutation.
	if err = s.saveResourceJournal(ctx, a.journal); err == nil {
		for i := range a.journal.Entries {
			if a.journal.Entries[i].Configuration || a.journal.Entries[i].StateRole != "" {
				continue
			}
			if err = a.swap(ctx, i); err != nil {
				break
			}
		}
	}
	if err != nil {
		if e := s.recoverResources(context.WithoutCancel(ctx)); e != nil {
			return nil, providerDegraded()
		}
		return nil, err
	}
	return a, nil
}
func (s *ProviderStore) noPending(ctx context.Context) error {
	for _, path := range []string{providerJournalPath, resourceJournalPath} {
		got, err := s.files.inspect(ctx, path)
		if err != nil {
			return err
		}
		if got.Present {
			return protocol.APIError{Code: protocol.CodeInvalidState, Message: "resource recovery or activation in progress"}
		}
	}
	return nil
}
func (s *ProviderStore) saveResourceJournal(ctx context.Context, j resourceJournal) error {
	b, err := json.Marshal(j)
	if err != nil {
		return err
	}
	old, err := s.files.inspect(ctx, resourceJournalPath)
	if err != nil {
		return err
	}
	return s.files.write(ctx, resourceJournalPath, b, old)
}
func (a *ResourceActivation) swap(ctx context.Context, i int) error {
	e := &a.journal.Entries[i]
	s := a.prepared.store
	target, err := e.target()
	if err != nil {
		return err
	}
	e.BackupIntent = true
	if err = s.saveResourceJournal(ctx, a.journal); err != nil {
		return err
	}
	if e.Old.Present {
		if err = s.files.move(ctx, target, e.Old, e.backupPath(), providerObject{}); err != nil {
			return err
		}
	}
	e.BackupDone = true
	e.SwapIntent = true
	if err = s.saveResourceJournal(ctx, a.journal); err != nil {
		return err
	}
	if err = s.files.move(ctx, e.candidatePath(), e.New, target, providerObject{}); err != nil {
		return err
	}
	e.SwapDone = true
	return s.saveResourceJournal(ctx, a.journal)
}

// Recheck confirms the exact swapped objects before config publication.
func (a *ResourceActivation) Recheck(ctx context.Context) error {
	if a == nil || a.prepared == nil {
		return dataError("resource activation unavailable")
	}
	s := a.prepared.store
	release, err := s.acquire(ctx)
	if err != nil {
		return err
	}
	defer release()
	if a.settled {
		return dataError("resource activation settled")
	}
	return a.recheck(ctx)
}
func (a *ResourceActivation) recheck(ctx context.Context) error {
	targets := map[string]providerObject{}
	for _, e := range a.journal.Entries {
		path, err := e.target()
		if err != nil {
			return err
		}
		wantTarget := e.New
		wantCandidate := providerObject{}
		wantBackup := e.Old
		if !e.SwapDone {
			wantTarget = e.Old
			wantCandidate = e.New
			wantBackup = providerObject{}
		} else {
			targets[path] = e.New
		}
		for path, want := range map[string]providerObject{path: wantTarget, e.candidatePath(): wantCandidate, e.backupPath(): wantBackup, e.markerPath(): e.Marker} {
			got, err := a.prepared.store.files.inspect(ctx, path)
			if err != nil {
				return err
			}
			if got != want {
				return providerConflict()
			}
		}
	}
	for _, source := range a.prepared.sources {
		want := source.object
		if replacement, ok := targets[source.path]; ok {
			want = replacement
		}
		got, err := a.prepared.store.files.inspect(ctx, source.path)
		if err != nil {
			return err
		}
		if got != want {
			return providerConflict()
		}
	}
	return nil
}

// Finish makes the whole new set authoritative only after config publication.
// A durable done is irreversible: ambiguous cleanup retains new authority.
func (a *ResourceActivation) Finish(ctx context.Context) error {
	if a == nil || a.prepared == nil {
		return dataError("resource activation unavailable")
	}
	s := a.prepared.store
	release, err := s.acquire(ctx)
	if err != nil {
		return err
	}
	defer release()
	if a.settled {
		return dataError("resource activation settled")
	}
	if err = a.recheck(ctx); err != nil {
		return err
	}
	for _, entry := range a.journal.Entries {
		if !entry.SwapDone {
			return dataError("resource activation is incomplete")
		}
	}
	a.journal.Done = true
	if len(a.journal.Entries) > 0 {
		if err = s.saveResourceJournal(ctx, a.journal); err != nil {
			// A write may have replaced the journal before reporting a sync or
			// close error. Never roll back a visible done record.
			if observed, readErr := s.loadResourceJournal(context.WithoutCancel(ctx)); readErr == nil {
				a.committed = observed.Done
				a.journal.Done = observed.Done
			}
			return providerDegraded()
		}
		a.committed = true
		if err = s.recoverResources(context.WithoutCancel(ctx)); err != nil {
			return providerDegraded()
		}
	}
	a.settled = true
	return nil
}

// Committed reports irreversible new-set authority, including cleanup failures.
func (a *ResourceActivation) Committed() bool { return a != nil && a.committed }

// PublishState swaps only the sealed daemon state participants, after the
// generated configuration has been validated and published. Memory publication
// must wait for Finish and its durable done authority.
func (a *ResourceActivation) PublishState(ctx context.Context) error {
	if a == nil || a.prepared == nil {
		return dataError("resource activation unavailable")
	}
	s := a.prepared.store
	release, err := s.acquire(ctx)
	if err != nil {
		return err
	}
	defer release()
	if a.settled {
		return dataError("resource activation settled")
	}
	if err = a.recheck(ctx); err != nil {
		return err
	}
	_, configuration, err := a.configEntry()
	if err != nil {
		return err
	}
	if !configuration.SwapDone {
		return dataError("activation configuration is unpublished")
	}
	for i, entry := range a.journal.Entries {
		if entry.StateRole != "" && !entry.SwapDone {
			if err = a.swap(ctx, i); err != nil {
				return err
			}
		}
	}
	return a.recheck(ctx)
}

// Restore ignores caller cancellation once rollback ownership is accepted.
func (a *ResourceActivation) Restore(ctx context.Context) error {
	if a == nil || a.prepared == nil {
		return dataError("resource activation unavailable")
	}
	ctx = context.WithoutCancel(ctx)
	s := a.prepared.store
	release, err := s.acquire(ctx)
	if err != nil {
		return err
	}
	defer release()
	if a.settled {
		return nil
	}
	if a.journal.Done {
		return providerDegraded()
	}
	if err = s.recoverResources(ctx); err != nil {
		return providerDegraded()
	}
	a.settled = true
	return nil
}

func (s *ProviderStore) loadResourceJournal(ctx context.Context) (resourceJournal, error) {
	var j resourceJournal
	b, err := s.files.read(ctx, resourceJournalPath, 1<<20)
	if err != nil {
		return j, err
	}
	if err = resourceJournalShape(b); err != nil {
		return j, dataError("invalid resource journal shape")
	}
	d := json.NewDecoder(bytes.NewReader(b))
	if err = uniqueProviderJSON(d, 0); err != nil {
		return j, dataError("invalid resource journal")
	}
	if _, err = d.Token(); err != io.EOF {
		return j, dataError("invalid resource journal")
	}
	d = json.NewDecoder(bytes.NewReader(b))
	d.DisallowUnknownFields()
	if err = d.Decode(&j); err != nil {
		return j, dataError("invalid resource journal")
	}
	if j.Schema != "mihari.resource-activation/v1" || len(j.Entries) == 0 || len(j.Entries) > 265 {
		return j, dataError("invalid resource journal")
	}
	paths := map[string]bool{}
	identities := map[string]bool{}
	configurations := 0
	roles := map[resourceStateRole]bool{}
	for _, e := range j.Entries {
		if e.StateRole != "" {
			if roles[e.StateRole] {
				return j, dataError("duplicate activation state role")
			}
			roles[e.StateRole] = true
		}
		if e.Configuration {
			configurations++
		}
		target, e2 := e.target()
		if e2 != nil {
			return j, e2
		}
		if paths[target] || paths[e.Transaction] || !profileIDPattern.MatchString(e.Transaction) {
			return j, dataError("duplicate resource activation identity")
		}
		paths[target] = true
		paths[e.Transaction] = true
		if !e.New.Present || !e.Marker.Present || e.Marker.SHA256 != providerDigest([]byte(e.Transaction)) || e.BackupDone && !e.BackupIntent || e.SwapIntent && !e.BackupDone || e.SwapDone && !e.SwapIntent || e.RestoreDone && !e.RestoreIntent || j.Done && (!e.SwapDone || e.RestoreIntent) {
			return j, dataError("invalid resource activation action")
		}
		for _, o := range []providerObject{e.Old, e.New, e.Marker} {
			if !validProviderObject(o) || o.Present && o.BootID != e.Marker.BootID {
				return j, dataError("invalid resource activation object")
			}
			if o.Present {
				key := o.BootID + "/" + o.Identity
				if identities[key] {
					return j, dataError("aliased resource activation object")
				}
				identities[key] = true
			}
		}
	}
	if configurations != 1 {
		if configurations != 0 {
			return j, dataError("invalid resource activation configuration")
		}
		for _, e := range j.Entries {
			if e.Geo == "" || e.Configuration || e.StateRole != "" {
				return j, dataError("invalid resource activation configuration")
			}
		}
	}
	return j, nil
}

func resourceJournalShape(b []byte) error {
	// Existing v1 journals predate the finite state_role field. Only its
	// omission means the legacy resource-only role; null/unknown fields and
	// all other omissions still fail the exact shape validator.
	var members map[string]json.RawMessage
	if err := json.Unmarshal(b, &members); err != nil {
		return err
	}
	var entries []map[string]json.RawMessage
	if err := json.Unmarshal(members["entries"], &entries); err != nil {
		return err
	}
	for _, entry := range entries {
		if entry == nil {
			return os.ErrInvalid
		}
		if _, exists := entry["state_role"]; !exists {
			entry["state_role"] = json.RawMessage(`""`)
		}
	}
	encoded, err := json.Marshal(entries)
	if err != nil {
		return err
	}
	members["entries"] = encoded
	encoded, err = json.Marshal(members)
	if err != nil {
		return err
	}
	return providerJSONShape(encoded, reflect.TypeOf(resourceJournal{}))
}
func (s *ProviderStore) recoverResources(ctx context.Context) error {
	j, err := s.loadResourceJournal(ctx)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	for i := len(j.Entries) - 1; i >= 0; i-- {
		e := &j.Entries[i]
		target, err := e.target()
		if err != nil {
			return err
		}
		marker, err := s.files.inspect(ctx, e.markerPath())
		if err != nil {
			return err
		}
		if !sameProviderObject(marker, e.Marker) {
			return dataError("resource activation marker changed")
		}
		actual, err := s.files.inspect(ctx, target)
		if err != nil {
			return err
		}
		backup, err := s.files.inspect(ctx, e.backupPath())
		if err != nil {
			return err
		}
		candidate, err := s.files.inspect(ctx, e.candidatePath())
		if err != nil {
			return err
		}
		if backup.Present && !sameProviderObject(backup, e.Old) || candidate.Present && !sameProviderObject(candidate, e.New) {
			return dataError("resource activation staging changed")
		}
		if j.Done {
			if !sameProviderObject(actual, e.New) {
				return dataError("committed resource activation changed")
			}
		} else {
			if !e.BackupIntent && !sameProviderObject(actual, e.Old) || !e.SwapIntent && sameProviderObject(actual, e.New) || e.RestoreDone && !sameProviderObject(actual, e.Old) {
				return dataError("resource activation action mismatch")
			}
			if actual.Present && !sameProviderObject(actual, e.Old) && !sameProviderObject(actual, e.New) {
				return dataError("resource activation target changed")
			}
			if e.Old.Present && !sameProviderObject(actual, e.Old) && !sameProviderObject(backup, e.Old) {
				return dataError("resource activation backup missing")
			}
			if actual.Present && sameProviderObject(actual, e.Old) && backup.Present {
				return dataError("aliased resource activation backup")
			}
			if !e.RestoreIntent {
				e.RestoreIntent = true
				if err = s.saveResourceJournal(ctx, j); err != nil {
					return err
				}
			}
			if backup.Present {
				if err = s.files.move(ctx, e.backupPath(), backup, target, actual); err != nil {
					return err
				}
			} else if !e.Old.Present && actual.Present {
				if err = s.files.remove(ctx, target, actual); err != nil {
					return err
				}
			}
			if !e.RestoreDone {
				e.RestoreDone = true
				if err = s.saveResourceJournal(ctx, j); err != nil {
					return err
				}
			}
		}
	}
	// All targets have converged before any backup/candidate cleanup. Journal and
	// marker remain until every known object has been removed durably.
	for _, e := range j.Entries {
		for path, want := range map[string]providerObject{e.backupPath(): e.Old, e.candidatePath(): e.New} {
			got, err := s.files.inspect(ctx, path)
			if err != nil {
				return err
			}
			if got.Present {
				if !sameProviderObject(got, want) {
					return dataError("resource activation cleanup changed")
				}
				if err = s.files.remove(ctx, path, got); err != nil {
					return err
				}
			}
		}
	}
	journal, err := s.files.inspect(ctx, resourceJournalPath)
	if err != nil {
		return err
	}
	return s.files.remove(ctx, resourceJournalPath, journal)
}
