package core

import (
	"context"
	"crypto/sha256"
	"errors"
	"testing"

	"github.com/mihari-proxy/mihari/internal/subscription"
)

func TestResourceActivation_ExcludesCorePublication(t *testing.T) {
	s := newMemoryStore()
	seedInstalledReceipt(t, s, "trusted")
	f := &memoryConfigs{s: s}
	x := &TrustedExecution{store: s, files: f}
	a, err := x.BeginResourceActivation(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	defer a.Close()
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	_, err = x.RestoreConfig(ctx, []byte("must not publish"))
	if !errors.Is(err, context.Canceled) || f.writes != 0 {
		t.Fatal("publication entered during activation")
	}
	// Directly observe the shared gate, avoiding timing-based assertions.
	ctx, cancel = context.WithCancel(context.Background())
	cancel()
	release, err := s.execution().acquire(ctx)
	if release != nil {
		release()
	}
	if !errors.Is(err, context.Canceled) {
		t.Fatal("activation did not exclude commands")
	}
	select {
	case <-s.execution().token:
		s.execution().token <- struct{}{}
		t.Fatal("activation did not retain execution ownership")
	default:
	}
}

func TestResourceActivation_UsesAlreadyOwnedExecutionForValidation(t *testing.T) {
	s := newMemoryStore()
	seedInstalledReceipt(t, s, "trusted")
	f := &memoryConfigs{s: s}
	x := &recordedExecutor{store: s}
	trusted := &TrustedExecution{store: s, files: f, executor: x}
	activation, err := trusted.BeginResourceActivation(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	defer activation.Close()

	content := []byte("fixed resource config")
	if err = activation.validateOwned(context.Background(), content, sha256.Sum256(content), s.location(), s.bindingIdentity()); err != nil {
		t.Fatal(err)
	}
	if len(x.configHashes) != 1 || x.configHashes[0] != digest(content) {
		t.Fatal("validation did not execute the exact generated bytes")
	}
}

func TestResourceActivation_RejectsUntypedOrDifferentStore(t *testing.T) {
	s := newMemoryStore()
	seedInstalledReceipt(t, s, "trusted")
	trusted := &TrustedExecution{store: s, files: &memoryConfigs{s: s}}
	activation, err := trusted.BeginResourceActivation(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	defer activation.Close()
	if err = activation.Validate(context.Background(), (*subscription.ResourceActivation)(nil)); err == nil {
		t.Fatal("nil typed activation accepted")
	}
	content := []byte("config")
	if err = activation.validateOwned(context.Background(), content, sha256.Sum256(content), "/other/data", "root-2"); err == nil {
		t.Fatal("different resource store accepted")
	}
}
