package core

import (
	"context"
	"crypto/sha256"
	"errors"
	"github.com/mihari-proxy/mihari/internal/control/protocol"
	"os"
	"path/filepath"
	"sync"
)

type configFiles interface {
	prepare(context.Context, []byte) (*ConfigCapability, error)
	read(context.Context) ([]byte, error)
	write(context.Context, []byte) (*ConfigCapability, error)
	bind(context.Context, [32]byte) (*ConfigCapability, error)
	remove(context.Context, *ConfigCapability) error
}

// TrustedExecution binds core and generated configuration IO to one trusted D.
// Unix construction borrows D; no public fields can replace its authorities.
type TrustedExecution struct {
	store     ProvenanceStore
	files     configFiles
	executor  VerifiedExecutor
	mu        sync.Mutex
	committed [32]byte
	ready     bool
}

// GeneratedConfig retains the exact generated bytes selected for validation.
type GeneratedConfig struct {
	owner   *TrustedExecution
	cap     *ConfigCapability
	content []byte
	hash    [32]byte
}

// Hash is the hash of the generated bytes, never a caller-supplied trust root.
func (g *GeneratedConfig) Hash() [32]byte { return g.hash }

// Path is the selected candidate path, for fixed-path reload adapters only.
func (g *GeneratedConfig) Path(ctx context.Context) (string, error) {
	return g.cap.verify(ctx, g.owner.store.coreStore().location(), false)
}

// Close retires a generated candidate; identity mismatch leaves the object intact.
func (g *GeneratedConfig) Close() error {
	if g == nil {
		return nil
	}
	e := g.owner.files.remove(context.Background(), g.cap)
	return errors.Join(e, g.cap.Close())
}

// Provenance returns the fixed-role store for startup recovery under the lease.
func (t *TrustedExecution) Provenance() ProvenanceStore { return t.store }

// Installer returns the root installer; path/args Runner is never used.
func (t *TrustedExecution) Installer() Installer {
	return Installer{Provenance: t.store, GeneratedConfig: t.CommittedConfig, Executor: t.executor}
}

// PrepareGenerated receives fresh generated bytes from Manager's generator.
// The caller's revision check remains in the mutation coordinator.
func (t *TrustedExecution) PrepareGenerated(ctx context.Context, generated []byte) (*GeneratedConfig, error) {
	if len(generated) == 0 {
		return nil, dataFailure("generated configuration is empty")
	}
	content := append([]byte(nil), generated...)
	hash := sha256.Sum256(content)
	cap, e := t.files.prepare(ctx, content)
	if e != nil {
		return nil, e
	}
	g := &GeneratedConfig{owner: t, cap: cap, content: content, hash: hash}
	v, e := OpenInstalledCore(ctx, t.store)
	if e != nil {
		_ = g.Close()
		return nil, e
	}
	defer func() { _ = v.Close() }() // Read-only capability: no pending writes; closure cannot change the operation result.
	if e = ValidateVerifiedConfig(ctx, v, cap, t.executor); e != nil {
		_ = g.Close()
		return nil, e
	}
	return g, nil
}

// Publish verifies the selected candidate again and atomically writes those same bytes.
// Manager invokes this only after its mutation/revision check, then reloads.
func (t *TrustedExecution) Publish(ctx context.Context, g *GeneratedConfig, expected [32]byte) (*ConfigCapability, error) {
	release, e := t.store.coreStore().execution().acquire(ctx)
	if e != nil {
		return nil, e
	}
	defer release()
	if g == nil || g.owner != t || g.hash != expected || sha256.Sum256(g.content) != expected {
		return nil, dataFailure("generated configuration changed before commit")
	}
	if _, e := g.Path(ctx); e != nil {
		return nil, e
	}
	t.mu.Lock()
	ready := t.ready
	t.mu.Unlock()
	var previous []byte
	if ready {
		var e error
		previous, e = t.PreviousConfig(ctx)
		if e != nil {
			return nil, e
		}
	}
	cap, e := t.publishContent(ctx, g.content)
	if e == nil {
		return cap, nil
	}
	recoveryCtx := context.WithoutCancel(ctx)
	actual, readErr := t.files.read(recoveryCtx)
	if !ready || readErr != nil || (sha256.Sum256(actual) != g.hash && sha256.Sum256(actual) != sha256.Sum256(previous)) {
		return nil, protocol.APIError{Code: protocol.CodeDataFailure, Message: "configuration publication recovery could not be confirmed", Details: map[string]any{"degraded": true}}
	}
	restored, restoreErr := t.publishContent(recoveryCtx, previous)
	if restoreErr != nil {
		return nil, protocol.APIError{Code: protocol.CodeDataFailure, Message: "configuration publication recovery could not be confirmed", Details: map[string]any{"degraded": true}}
	}
	if closeErr := restored.Close(); closeErr != nil {
		return nil, errors.Join(e, closeErr)
	}
	return nil, e
}

// publishContent requires execution ownership; compensation must not reacquire it.
func (t *TrustedExecution) publishContent(ctx context.Context, b []byte) (*ConfigCapability, error) {
	cap, e := t.files.write(ctx, b)
	if e != nil {
		return nil, e
	}
	t.mu.Lock()
	t.committed = sha256.Sum256(b)
	t.ready = true
	t.mu.Unlock()
	return cap, nil
}

// PreviousConfig captures the last bound bytes for rollback under the mutation lease.
func (t *TrustedExecution) PreviousConfig(ctx context.Context) ([]byte, error) {
	cap, e := t.CommittedConfig(ctx)
	if e != nil {
		return nil, e
	}
	defer func() { _ = cap.Close() }() // Read-only capability: no pending writes; closure cannot change the operation result.
	if _, e = cap.verify(ctx, t.store.coreStore().location(), true); e != nil {
		return nil, e
	}
	b, e := t.files.read(ctx)
	if e != nil {
		return nil, e
	}
	if sha256.Sum256(b) != cap.hash {
		return nil, dataFailure("previous configuration changed during capture")
	}
	return b, nil
}

// RestoreConfig reinstalls bytes captured through PreviousConfig, then rebinds.
func (t *TrustedExecution) RestoreConfig(ctx context.Context, previous []byte) (*ConfigCapability, error) {
	release, e := t.store.coreStore().execution().acquire(ctx)
	if e != nil {
		return nil, e
	}
	defer release()
	return t.publishContent(ctx, previous)
}

// CommittedConfig requires the hash accepted by initialization or publication.
func (t *TrustedExecution) CommittedConfig(ctx context.Context) (*ConfigCapability, error) {
	t.mu.Lock()
	hash, ready := t.committed, t.ready
	t.mu.Unlock()
	if !ready {
		return nil, dataFailure("committed configuration not initialized")
	}
	return t.files.bind(ctx, hash)
}

// RunCommand obtains a fresh installed pair plus committed configuration for Start.
// release must run after OS Start, including any failed Start path.
func (t *TrustedExecution) RunCommand(ctx context.Context) (CoreCommand, func() error, error) {
	releaseExecution, e := t.store.coreStore().execution().acquire(ctx)
	if e != nil {
		return CoreCommand{}, nil, e
	}
	v, e := OpenInstalledCore(ctx, t.store)
	if e != nil {
		releaseExecution()
		return CoreCommand{}, nil, e
	}
	c, e := t.CommittedConfig(ctx)
	if e != nil {
		releaseExecution()
		return CoreCommand{}, nil, errors.Join(e, v.Close())
	}
	command, e := v.Command(ctx, CoreRun, c)
	release := func() error { defer releaseExecution(); return errors.Join(c.Close(), v.Close()) }
	if e != nil {
		return CoreCommand{}, nil, errors.Join(e, release())
	}
	return command, release, nil
}

// InitializeConfig validates and publishes already-generated startup bytes.
// A bootstrap may be accepted only when both installed provenance roles are absent.
func (t *TrustedExecution) InitializeConfig(ctx context.Context, generated []byte) error {
	if len(generated) == 0 {
		return dataFailure("generated configuration is empty")
	}
	content := append([]byte(nil), generated...)
	if _, e := t.InstalledAvailable(ctx); e != nil {
		return e
	}
	cap, e := t.files.prepare(ctx, content)
	if e != nil {
		return e
	}
	defer func() { _ = cap.Close() }()                                     // Read-only capability: no pending writes; closure cannot change the operation result.
	defer func() { _ = t.files.remove(context.WithoutCancel(ctx), cap) }() // Best-effort removal of the checked private staging inode; publication outcome is already known.
	v, e := OpenInstalledCore(ctx, t.store)
	if e == nil {
		defer func() { _ = v.Close() }() // Read-only capability: no pending writes; closure cannot change the operation result.
		if e = ValidateVerifiedConfig(ctx, v, cap, t.executor); e != nil {
			return e
		}
	} else if !errors.Is(e, os.ErrNotExist) {
		return e
	}
	committed, e := t.RestoreConfig(ctx, content)
	if e != nil {
		return e
	}
	return committed.Close()
}

// CheckPaths prevents a root assembly from mixing capabilities with another tree.
func (t *TrustedExecution) CheckPaths(root, binary, configuration string) error {
	if t == nil || t.store == nil || t.files == nil {
		return dataFailure("trusted core capability unavailable")
	}
	expected := t.store.coreStore().location()
	if filepath.Clean(root) != filepath.Clean(expected) || filepath.Clean(binary) != filepath.Join(expected, "bin", "mihomo") || filepath.Clean(configuration) != filepath.Join(expected, "runtime", "config.yaml") {
		return dataFailure("trusted core layout mismatch")
	}
	return nil
}

// InstalledAvailable distinguishes a true green install from a broken pair.
func (t *TrustedExecution) InstalledAvailable(ctx context.Context) (bool, error) {
	b, e := t.store.Inspect(ctx, InstalledBinary, "")
	if e != nil {
		return false, e
	}
	r, e := t.store.Inspect(ctx, InstalledReceipt, "")
	if e != nil {
		return false, e
	}
	if b.Present != r.Present {
		return false, dataFailure("incomplete installed core provenance pair")
	}
	if !b.Present {
		return false, nil
	}
	v, e := OpenInstalledCore(ctx, t.store)
	if e != nil {
		return false, e
	}
	return true, v.Close()
}
